name: Deploy TinyUrl App
on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t joeyschen/tinyurl  .
      - name: Publish image to docker hub
        run: docker push joeyschen/tinyurl:latest
    
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull joeyschen/tinyurl:latest
      - name: Delete old container
        run: docker rm -f tinyurl-container 
      - name: Run docker container
        run: docker run -d -p 3001:3001 --name tinyurl-container -e MONGO_PASSWORD='${{ secrets.MONGODB_PASSWORD }}' joeyschen/tinyurl
